import './src/styles/global.css'
import './src/styles/cabecalho.css'
import './src/styles/eventos.css'
import './src/styles/projetos-npi.css'
import './src/styles/projetos-paf.css'
import './src/styles/parcerias.css'
import './src/styles/rodape.css'